Dejting/Controllers/FriendRequestController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dejting.Models;
using Dejting.Repositories;


namespace Dejting.Controllers
{
    public class FriendRequestController : Controller
    {

        private AddFriendRepository AddFriendRepository;
        private UserRepository UserRepository;
        private FriendRepository FriendRepository; 

        public FriendRequestController() //konstruktor ska alltid se ut såhär 
        {
            ApplicationDbContext context = new ApplicationDbContext();
            AddFriendRepository = new AddFriendRepository(context);
            UserRepository = new UserRepository(context);
            FriendRepository = new FriendRepository(context);

        }
        // GET: FriendRequest
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SendRequest(string id)
        {
            FriendRequest FriendRequest = new FriendRequest();

            var userNameId = User.Identity.GetUserId();

            var fromUser = UserRepository.Get(userNameId);

            FriendRequest.From = fromUser;

            var toUser = UserRepository.Get(id.ToString());

            FriendRequest.To = toUser;
            
            var checklist = AddFriendRepository.GetAll();

            bool FriendRequestExist = false;


            foreach (var item in checklist)
            {

                if (fromUser.Id.Equals(item.To.Id) && toUser.Id.Equals(item.From.Id) || fromUser.Id.Equals(item.From.Id) && toUser.Id.Equals(item.To.Id))
                {
                    FriendRequestExist = true;
                }
            }

            if (FriendRequestExist == false)
            {
                AddFriendRepository.Add(FriendRequest);

                AddFriendRepository.Save();

                return View("Error");
            }
           
            else
            {
                return View("AlreadyFriends");
            }
        }

        //visar lista på vänförfrågningar 
        [HttpGet]
        public ActionResult RequestList()
        {   
            var anvandare = User.Identity.GetUserId();

            var requests = AddFriendRepository.GetAll().Where(request => request.To.Id == anvandare).ToList();

            

            //ska hämta till vilken dvs inloggade användaren 
            var anvandaretill = AddFriendRepository.GetAll().Where(x => x.To.Id == (anvandare)).Select(u=> u.From);

            var user = from a in UserRepository.GetAll().Where(x=>x.Id.Equals(anvandaretill)) select a;

            return View(requests);
        }



        //visar lista på mina vänner
        [HttpGet]
        public ActionResult FriendList()
        {
            var anvandare = User.Identity.GetUserId();

            //ska hämta till vilken dvs inloggade användaren 
            var anvandaretill = FriendRepository.GetAll().Where(x => x.Friend1.Id ==(anvandare)).Select(u => u.Friend2);

            var user = from a in UserRepository.GetAll().Where(x => x.Id.Equals(anvandaretill)) select a;





            var anvandaretill2 = FriendRepository.GetAll().Where(x => x.Friend2.Id == (anvandare)).Select(u => u.Friend1);

            var user2 = from a in UserRepository.GetAll().Where(x => x.Id.Equals(anvandaretill2)) select a;

            var total = anvandaretill.Concat(anvandaretill2);

            return View(total);
        }
        
        [HttpGet]
        public PartialViewResult Notification()
        {
 
            var requests = AddFriendRepository.GetAll().Where(request => request.To.Id == User.Identity.GetUserId()).ToList();

            var model = new BoolHolder();
            model.UserGotRequest = requests.Any();

            return PartialView("_Notification", model);
        }
    }
}

Dejting/Controllers/ProfileController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dejting.Models;
using Dejting.Repositories;
using Dejting.ViewModel;
using Dejting.ViewModel.Post;
using Dejting.ViewModel.Profilepage;

namespace Dejting.Controllers
{
    public class ProfileController : Controller
    {
        private UserRepository userRepository;
        private PostRepository postRepository;

        public ProfileController() //konstruktor ska alltid se ut såhär 
        {
            ApplicationDbContext context = new ApplicationDbContext();
            userRepository = new UserRepository(context);
            postRepository = new PostRepository(context);
        }

        // GET: Profile
        //ska visa lista på användare som söks 

         
        public ActionResult Index(string searchString)
        {
            var user = from a in userRepository.GetAll().Where(x => x.Synlighet == Synlighet.Synlig) select a;
            if (!String.IsNullOrEmpty(searchString))
            {
              user = user.Where(s => s.Email.Contains(searchString) && s.Synlighet == Synlighet.Synlig);
            }
            return View(user);    
         
        }

        //details för minSida
        public ActionResult Details()
        {
            var userId = User.Identity.GetUserId();
            var user = userRepository.Get(userId);

            var postList = postRepository.GetAll().Where(post => post.To.Id == userId).OrderByDescending(post => post.DateTime);
            var posts = postList.Select(post => new PostListViewModel()
            {
                Text = post.Text,
                Date = post.DateTime,
                FromName = post.From.Email,
                ToName = post.To.Email
            });


            var model = new ProfilepageDetailsViewModel
            {
                Id = userId,
                Email = user.Email,
                Stad = user.Stad,
                Alder = user.Alder,
                Kön = user.Kön,
                Synlighet = user.Synlighet,
                Posts = posts.ToList()
            };

            return View(model);
  
        }


        
        //visar profilbilden 
        public ActionResult ProfilBild(string id) 
        {

            var user = userRepository.Get(id);

            //får inte ha null värden därför kan man inte ta sig till min profil 
            //om man inte laggt till en profilbild

            if (user.Bild == null)
                return View("Edit");

            return File(user.Bild, user.ContentType); 
        }

        

        //edit
        public ActionResult Edit()
        {
            var id = User.Identity.GetUserId();
            ApplicationUser user = userRepository.Get(id);

            ProfilepageEditViewModel model = new ProfilepageEditViewModel
            {
                Id = id,
                Stad = user.Stad,
                Alder = user.Alder,
                Bild = user.Bild,
                Synlighet = user.Synlighet
            };

            return View(model); 
        }


        //ändrar och lägger till en bild
        [HttpPost]
        public ActionResult Edit(ProfilepageEditViewModel userEditModel, HttpPostedFileBase upload)
        {  
            if (ModelState.IsValid == false)
                return View();
            string id = User.Identity.GetUserId();
            ApplicationUser user = userRepository.Get(id);

            user.Alder = userEditModel.Alder;
            user.Stad = userEditModel.Stad;
            user.Synlighet = userEditModel.Synlighet;
     
            userRepository.Edit(user);

            //kollar bild inte är null 
            if(upload!= null && upload.ContentLength > 0  && upload.ContentType == "image/jpeg")
            {

                user.ContentType = upload.ContentType;
        
                //använder en binaryreader
                using (var reader = new BinaryReader(upload.InputStream))
                {
                  
                    user.Bild = reader.ReadBytes(upload.ContentLength);
                    userEditModel.Bild = user.Bild;
                  
                }
                userRepository.Save();

            }
            else
            {
                return View("ImageError");
            }
            return RedirectToAction("Details");

        }

        public PartialViewResult GetPosts(string id)
        {
            var postsForUser = postRepository.GetAll().Where(post => post.To.Id == id).OrderByDescending(post => post.DateTime);

            var posts = postsForUser.Select(post => new PostListViewModel()
            {
                Text = post.Text,
                Date = post.DateTime,
                FromName = post.From.Email,
                ToName = post.To.Email
            });

            return PartialView("_PostTable", posts);
        }

    }
}

Dejting/Views/Shared/Accept.cshtml
@{
    ViewBag.Title = "Accepted Friend";
}

<h2 class="text-success">Nu är ni vänner!</h2>

Dejting/Views/Shared/AlreadyFriends.cshtml
@{
    ViewBag.Title = "AlreadyFriends";
}


<h2 class="text-danger"> Du har redan skickat en förfrågan!</h2>

Dejting/Views/Shared/Decline.cshtml
@{
    ViewBag.Title = "Decline Friend";
}

<h2 class="text-danger">Vänförfrågan borttagen!</h2>

Dejting/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ColourDating", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" id="requestDiv">
                    @if (User.Identity.IsAuthenticated)
                    {

                    <li>@Html.ActionLink(Resources.Resource.Min_Profil, "Details", "Profile")</li>


                    <li>@Html.ActionLink(Resources.Resource.Sök_Användare, "Index", "Profile")</li>


                    <li>@Html.ActionLink(Resources.Resource.Mina_Vänner, "FriendList", "FriendRequest")</li>


                    <li>@Html.ActionLink(Resources.Resource.Vänförfrågningar, "requestList", "FriendRequest")</li>
                   

                     


                    }


                  
               </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    
    @{
        if (User.Identity.IsAuthenticated)
        {
            @Scripts.Render("~/Scripts/layout-script/layout.js");
        }
     }

</body>
</html>

Dejting/Views/Shared/_Notification.cshtml
@model Dejting.Models.BoolHolder

@{

    if (Model.UserGotRequest)
    {
                <li>@Html.ActionLink(Resources.Resource.Min_Profil, "Details", "Profile")</li>
                <li>@Html.ActionLink(Resources.Resource.Sök_Användare, "Index", "Profile")</li>
                <li>@Html.ActionLink(Resources.Resource.Mina_Vänner, "FriendList", "FriendRequest")</li>
                <li>@Html.ActionLink(Resources.Resource.Vänförfrågningar, "requestList", "FriendRequest")</li>
               
                <li>@Html.ActionLink("Du har vänförfrågan", "requestList", "FriendRequest", null,  new { @style = "color:red;" })</li>
    }
    else
    {
                <li>@Html.ActionLink(Resources.Resource.Min_Profil, "Details", "Profile")</li>
                <li>@Html.ActionLink(Resources.Resource.Sök_Användare, "Index", "Profile")</li>
                <li>@Html.ActionLink(Resources.Resource.Mina_Vänner, "FriendList", "FriendRequest")</li>
                <li>@Html.ActionLink(Resources.Resource.Vänförfrågningar, "requestList", "FriendRequest")</li>
    }

}

Dejting/Views/Shared/_PostList.cshtml
@model IEnumerable<Dejting.Models.Post>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateTime)
        </th>
        <th></th>
    </tr>
   
@foreach (var item in Model) {
    
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateTime)
        </td>
    </tr>
}

</table>